"""empty message

Revision ID: 1532b142af8e
Revises: 93d61fc04b1f
Create Date: 2022-08-03 20:42:01.723770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1532b142af8e'
down_revision = '93d61fc04b1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('jobtitle', sa.String(length=50), nullable=False))
    op.add_column('jobs', sa.Column('companies_id', sa.Integer(), nullable=False))
    op.drop_constraint('jobs_snowparks_id_fkey', 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'companies', ['companies_id'], ['id'])
    op.drop_column('jobs', 'snowparks_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('snowparks_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key('jobs_snowparks_id_fkey', 'jobs', 'snowparks', ['snowparks_id'], ['id'])
    op.drop_column('jobs', 'companies_id')
    op.drop_column('jobs', 'jobtitle')
    # ### end Alembic commands ###
