"""empty message

Revision ID: ad1a0fc3a3f5
Revises: f738d36bbb1b
Create Date: 2022-08-05 14:01:01.719321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad1a0fc3a3f5'
down_revision = 'f738d36bbb1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('country_flag', sa.String(length=100), nullable=False))
    op.alter_column('snowparks', 'comment',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('snowparks', 'comment',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
    op.drop_column('country', 'country_flag')
    # ### end Alembic commands ###
