"""empty message

Revision ID: f738d36bbb1b
Revises: 784befd41412
Create Date: 2022-08-04 21:35:24.857089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f738d36bbb1b'
down_revision = '784befd41412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snowparks', sa.Column('parkweb', sa.String(length=80), nullable=True))
    op.add_column('snowparks', sa.Column('image_url', sa.String(length=300), nullable=True))
    op.add_column('snowparks', sa.Column('comment', sa.String(length=300), nullable=True))
    op.add_column('snowparks', sa.Column('machines', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snowparks', 'machines')
    op.drop_column('snowparks', 'comment')
    op.drop_column('snowparks', 'image_url')
    op.drop_column('snowparks', 'parkweb')
    # ### end Alembic commands ###
